cpuidle: remove unused variable
drivers/cpuidle/cpuidle.c:649:6: error: unused variable 'cpu' [-Werror,-Wunused-variable]
        int cpu;
            ^

Signed-off-by: Marco Zanin <mrczn.bb@gmail.com>